server:
  port: 8000

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: fearless-draft

  jackson:
    serialization:
      fail-on-empty-beans: false

  websocket:
    message-size-limit: 128000
    send-time-limit: 20s


  data:
    redis:
      host: localhost
      port: 6379